apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-a3uu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-a3uu
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-a3uu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-a3uu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-a3uu
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-eqqf-tenant/rhtap-demo-app/hacbs-test-project-a3uu@sha256:8d63a034549fb397223e0039db8ae731b435a4230384204815d5ecaf3227a1bb
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
